# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: sarajanedeveloper@gmail.com
author_name: SaraJane
contract_name: saver_contract
deployment_language: python
preset_name: production
project_name: Saver-contracts

